---
galaxy_info:
  author: Josh Noll
  
  description: Installs a docker container with a Tailscale sidecar for networking.
  
  license: MIT

  min_ansible_version: 2.16.9

  galaxy_tags:
    - homelab
    - tailscale
    - ubuntu
    - fedora
    - docker
    - containers
    - infrastructure
    - linux

dependencies: []
...
